/**
 * Compatibility database — shared schema, parser and aggregation helpers.
 *
 * One Markdown report per tested game lives in `src/content/compat/` with
 * frontmatter matching `CompatFrontmatter` below. Reports are parsed at build
 * time (no runtime API calls); the build fails on invalid reports
 * (see `scripts/validate-compat.mjs`).
 *
 * The site serves this data through TWO pre-parsed payloads generated by
 * scripts/export-site-compat-json.mjs — the client never parses markdown:
 *
 *   - compat-index.json — a slim index of every TESTED game (key, title,
 *     titleId, cover, precomputed overall + per-OS status, report counts,
 *     latest test date, carousel screenshots). Home and the compatibility
 *     page consume this via the `CompatIndexGame` helpers below.
 *   - compat/<KEY>.json — one file per game with its full reports (notes,
 *     hardware, score, source, …). Only the game page fetches it; the
 *     build-time bundle snapshot (src/lib/compat-seed.ts) covers 404s,
 *     legacy slug links and dev-without-build.
 *
 * A game has one report per (game, OS), set from a verified compatibility
 * issue via the conversion workflow (issue template → maintainer verification
 * → merged PR). A game's status on "Any" is the BEST result across its per-OS
 * tests; within an OS it is that OS's report status
 * (see `displayStatus` / `aggregateStatus`).
 */

export const STATUSES = ["doesnt-boot", "logo", "main-menu", "in-game"] as const;
export type Status = (typeof STATUSES)[number];
export type DisplayStatus = Status | "untested";

export const OSES = ["windows", "linux", "macos"] as const;
export type Os = (typeof OSES)[number];

/** Title IDs look like PPSA12345 (dash optional). */
export const TITLE_ID_REGEX = /^PPSA-?\d{5}$/i;

/** Frontmatter schema for a compatibility report. */
export interface CompatFrontmatter {
  /** Human-readable game title. */
  title: string;
  /** PS5 title ID (PPSA-XXXXX) — required. */
  titleId: string;
  status: Status;
  /** KytyPS5 build the game was tested on (commit or release). */
  testedVersion: string;
  testedDate: string;
  /** OS this test ran on — required: every stored game has one report per OS. */
  os: Os;
  hardware?: string;
  /** Optional 1–5 score. */
  score?: number;
  /** Optional tested game version (e.g. "1.004"). */
  gameVersion?: string;
  /** Optional screenshot shown on the homepage carousel — a path relative to
      public/screenshots/ (e.g. "screenshots/ps5-01.png") or an absolute URL. */
  screenshot?: string;
  /**
   * True when a maintainer attached the screenshot to a report that already
   * carries a community status. A screenshot NEVER implies a status by itself
   * — the validator requires this flag (plus a linked community source) on
   * any report with a screenshot, so the old "inferred from screenshots"
   * reports can't come back.
   */
  screenshotVerified?: boolean;
  /**
   * Screenshot URLs copied from the source issue at conversion time — they
   * stay affiliated with their report (and its OS) and are hotlinked on the
   * game page, never downloaded into the repo. The validator requires each to
   * be an http(s) URL and the report to link its community source.
   */
  screenshots?: string[];
}

/** Provenance of a report — issue link when community-filed. */
export interface ReportSource {
  label: string;
  url?: string;
}

export interface CompatReport extends CompatFrontmatter {
  slug: string;
  /** Markdown body after the frontmatter (source line stripped). */
  notes: string;
  /** Where the report came from (issue link, repository screenshots, …). */
  source?: ReportSource;
}

/** Canonical per-game page key: title ID when known, else the report slug. */
export function gamePageKey(report: Pick<CompatReport, "titleId" | "slug">, game?: { titleId?: string }): string {
  return game?.titleId ?? report.titleId ?? report.slug;
}

/**
 * Status ladder (4 tiers) — the exact options of the Game Emulation Status
 * Report issue template on the KytyPS5 repo, with the community-convention
 * colors:
 *   grey   — Doesn't boot: shows no first logo or startup screen
 *   red    — Logo:         shows a logo / startup screen, no main menu
 *   orange — Main menu:    reaches its menus, does not enter gameplay
 *   green  — In game:      reaches controllable gameplay (bugs may remain)
 */
export const STATUS_META: Record<DisplayStatus, { label: string; color: string; description: string }> = {
  "doesnt-boot": {
    label: "Doesn't boot",
    color: "#9ca3af",
    description: "The game does not show its first logo or startup screen.",
  },
  logo: {
    label: "Logo",
    color: "#f87171",
    description: "The game shows a logo or startup screen but does not reach the main menu.",
  },
  "main-menu": {
    label: "Main menu",
    color: "#fb923c",
    description: "The game reaches its menus but does not enter gameplay.",
  },
  "in-game": {
    label: "In game",
    color: "#4ade80",
    description: "The game reaches controllable gameplay, even if bugs prevent completion.",
  },
  untested: {
    label: "Not tested",
    color: "#64748b",
    description: "No compatibility report yet.",
  },
};

type OsReport = Pick<CompatReport, "status" | "os">;

/** Reports that apply within an OS scope (`"all"` = every report). */
export function reportsForOs(reports: readonly OsReport[], os: Os | "all"): readonly OsReport[] {
  return os === "all" ? reports : reports.filter((r) => r.os === os);
}

/** Group reports by OS for per-OS aggregation (unknown OS gets its own bucket). */
function groupByOs(reports: readonly OsReport[]): Map<string, OsReport[]> {
  const groups = new Map<string, OsReport[]>();
  for (const r of reports) {
    const key = r.os ?? "unknown";
    const list = groups.get(key) ?? [];
    list.push(r);
    groups.set(key, list);
  }
  return groups;
}

/**
 * A game's status on "Any": the BEST result across its per-OS tests (each
 * OS's reports aggregate first — one verified report per OS). A game that is
 * playable on Windows but only boots on macOS shows Playable overall — the
 * best of any test done.
 */
export function displayStatus(reports: readonly OsReport[]): DisplayStatus {
  let best: Status | null = null;
  for (const group of groupByOs(reports).values()) {
    const status = aggregateStatus(group);
    if (best === null || STATUSES.indexOf(status) > STATUSES.indexOf(best)) best = status;
  }
  return best ?? "untested";
}

/**
 * A game's status within an OS scope: "all" = best across tested OSes (same
 * as `displayStatus`); a specific OS = that OS's report status, or `untested`
 * when none exist. Used by the game page (per-OS slots + overall badge).
 */
export function displayStatusForOs(reports: readonly OsReport[], os: Os | "all"): DisplayStatus {
  if (os === "all") return displayStatus(reports);
  const scoped = reportsForOs(reports, os);
  return scoped.length > 0 ? aggregateStatus(scoped) : "untested";
}

/** Per-OS status breakdown for a game (drives the game page's OS slots). */
export function perOsStatuses(reports: readonly OsReport[]): Record<Os, DisplayStatus> {
  return {
    windows: displayStatusForOs(reports, "windows"),
    linux: displayStatusForOs(reports, "linux"),
    macos: displayStatusForOs(reports, "macos"),
  };
}

/* ------------------------------------------------------------------ */
/* Slim index (compat-index.json) — the list-view payload.            */
/* ------------------------------------------------------------------ */

/** One row of the slim compatibility index (written by the site export). */
export interface CompatIndexGame {
  /** Canonical route key (the game's title ID, normalized). */
  key: string;
  /** Display name. */
  title: string;
  titleId?: string;
  cover?: string;
  /** Best status across tested OSes — never "untested" (tested games only). */
  overall: Status;
  /** Per-OS status; an OS key present means a report exists for it. */
  os: Partial<Record<Os, Status>>;
  /** Per-OS report counts (the row's "N reports" text). */
  reportCounts: Partial<Record<Os, number>>;
  /** Newest testedDate across the game's reports. */
  latestTested?: string;
  /** Reports carrying a screenshot (homepage carousel), newest first. */
  screenshots?: { title: string; screenshot: string; testedDate?: string }[];
}

/** Shape of public/data/compat-index.json. */
export interface CompatIndexPayload {
  version: number;
  games: CompatIndexGame[];
}

/** Shape of public/data/compat/<KEY>.json (the per-game detail payload). */
export interface CompatGamePayload {
  version: number;
  key: string;
  title: string;
  titleId?: string;
  reports: CompatReport[];
}

/** A game's status inside an OS scope, from the slim index. */
export function osStatus(entry: CompatIndexGame, os: Os | "all"): DisplayStatus {
  if (os === "all") return entry.overall;
  return entry.os[os] ?? "untested";
}

export interface IndexFilters {
  status?: "all" | DisplayStatus;
  os?: Os | "all";
  query?: string;
}

/**
 * Filter the slim index. Status is always evaluated inside the active OS
 * scope, so e.g. `main-menu` + `linux` only matches games with a Linux
 * report voting main menu — a game whose only main-menu report is Windows
 * does not match. Pure + testable; the page only renders the result.
 */
export function filterCompatIndex(
  index: readonly CompatIndexGame[],
  { status = "all", os = "all", query = "" }: IndexFilters = {},
): CompatIndexGame[] {
  const q = query.trim().toLowerCase();
  return index.filter((entry) => {
    // The OS selection scopes STATUS evaluation — it never drops games itself.
    const scoped = osStatus(entry, os);
    if (status === "untested" && scoped !== "untested") return false;
    if (status !== "all" && status !== "untested" && scoped !== status) return false;
    if (q && !entry.title.toLowerCase().includes(q) && !(entry.titleId ?? entry.key).toLowerCase().includes(q)) {
      return false;
    }
    return true;
  });
}

/**
 * Aggregate slim-index stats within an OS scope (powers the stats strip and
 * the filter-pill counts). "Any" counts a game's best-across-OS status; a
 * specific OS counts that OS's report status. A game is "tested" only when
 * it has a report for that OS; everything else counts as not tested there.
 */
export function compatIndexStats(
  index: readonly CompatIndexGame[],
  os: Os | "all" = "all",
): { total: number; tested: number; untested: number; counts: Record<Status, number> } {
  const counts = Object.fromEntries(STATUSES.map((s) => [s, 0])) as Record<Status, number>;
  let tested = 0;
  for (const entry of index) {
    const status = osStatus(entry, os);
    if (status === "untested") continue;
    tested += 1;
    counts[status] += 1;
  }
  return { total: index.length, tested, untested: index.length - tested, counts };
}

/**
 * Overall stats for the homepage preview bar — one entry per tested game,
 * counted by its best-across-OS status.
 */
export function computeIndexStats(entries: readonly CompatIndexGame[]): {
  tested: number;
  counts: Record<Status, number>;
} {
  const counts = Object.fromEntries(STATUSES.map((s) => [s, 0])) as Record<Status, number>;
  for (const entry of entries) counts[entry.overall] += 1;
  return { tested: entries.length, counts };
}

/**
 * Aggregate a game's reports within one OS scope — the majority vote, with
 * ties broken toward the better status (higher on the ladder). The intake
 * pipeline keeps one verified report per (game, OS), so in practice this is
 * simply the verified report's status; the majority rule is a safe fallback
 * if multiple reports ever coexist.
 */
export function aggregateStatus(reports: readonly Pick<CompatReport, "status">[]): Status {
  if (reports.length === 0) return STATUSES[0];
  const counts = new Map<Status, number>();
  for (const r of reports) counts.set(r.status, (counts.get(r.status) ?? 0) + 1);
  let best: Status = reports[0].status;
  let bestCount = 0;
  let bestRank = -1;
  for (const [status, count] of counts) {
    const rank = STATUSES.indexOf(status);
    // More votes wins; on a tie the better status wins.
    if (count > bestCount || (count === bestCount && rank > bestRank)) {
      best = status;
      bestCount = count;
      bestRank = rank;
    }
  }
  return best;
}

/* ---------- Tiny frontmatter parser (no runtime deps, build-time only) ---------- */

function parseFrontmatter(raw: string): { data: Record<string, unknown>; body: string } {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!match) return { data: {}, body: raw.trim() };
  const data: Record<string, unknown> = {};
  for (const line of match[1].split(/\r?\n/)) {
    const idx = line.indexOf(":");
    if (idx < 0) continue;
    const key = line.slice(0, idx).trim();
    let value: unknown = line.slice(idx + 1).trim().replace(/^["']|["']$/g, "");
    if (value === "true") value = true;
    else if (value === "false") value = false;
    else if (/^\d+$/.test(String(value))) value = Number(value);
    else if (/^\[.*\]$/.test(String(value))) {
      // Flow-style array frontmatter (screenshots: ["url", …]) — URLs never
      // contain commas or quotes, so a simple split is safe.
      value = String(value)
        .slice(1, -1)
        .split(",")
        .map((v) => v.trim().replace(/^["']|["']$/g, ""))
        .filter(Boolean);
    }
    data[key] = value;
  }
  return { data, body: match[2].trim() };
}

/**
 * Extract a `> Source: [label](url)` or `> Source: label` line from the body.
 * The LAST such line wins: the report converter always appends the real source
 * at the end, so a `> Source:` blockquote typed inside a report's notes (e.g.
 * an "Extra notes" section quoting its own source) must not be mistaken for
 * the report's provenance.
 */
export function extractSource(raw: string): { source?: ReportSource; body: string } {
  const lines = raw.split(/\r?\n/);
  let sourceLine = -1;
  for (let i = 0; i < lines.length; i++) {
    if (/^>\s*Source:/.test(lines[i])) sourceLine = i;
  }
  if (sourceLine === -1) return { body: raw };
  const text = lines[sourceLine].replace(/^>\s*Source:\s*/i, "").trim();
  const link = text.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
  const source: ReportSource = link
    ? { label: link[1], url: link[2] }
    : { label: text };
  const body = lines.filter((_, idx) => idx !== sourceLine).join("\n").trim();
  return { source, body };
}

/** Validate and normalize a raw report file. Throws with a readable message. */
export function parseCompatReport(raw: string, slug: string): CompatReport {
  const { data, body: rawBody } = parseFrontmatter(raw);
  const { source, body } = extractSource(rawBody);

  const errors: string[] = [];
  const title = typeof data.title === "string" && data.title.trim() ? data.title : "";
  const status = data.status as Status;
  const testedVersion = typeof data.testedVersion === "string" ? data.testedVersion : "";
  const testedDate = typeof data.testedDate === "string" ? data.testedDate : "";
  const titleId = typeof data.titleId === "string" && data.titleId.trim() ? data.titleId : "";
  const os = data.os as CompatFrontmatter["os"] | undefined;
  const hardware = typeof data.hardware === "string" ? data.hardware : undefined;
  const score = typeof data.score === "number" ? data.score : undefined;
  const gameVersion =
    typeof data.gameVersion === "string" && data.gameVersion.trim() ? data.gameVersion : undefined;
  const screenshot =
    typeof data.screenshot === "string" && data.screenshot.trim() ? data.screenshot : undefined;
  const screenshotVerified =
    typeof data.screenshotVerified === "boolean" ? data.screenshotVerified : undefined;
  const screenshots = Array.isArray(data.screenshots)
    ? data.screenshots.filter((s): s is string => typeof s === "string")
    : undefined;

  if (!title) errors.push("missing required frontmatter field: title");
  if (!titleId) errors.push("missing required frontmatter field: titleId");
  else if (!TITLE_ID_REGEX.test(titleId)) errors.push(`titleId must look like PPSA-XXXXX, got "${titleId}"`);
  if (!STATUSES.includes(status)) {
    errors.push(`status must be one of ${STATUSES.join(" | ")}, got "${String(status)}"`);
  }
  if (!testedVersion) errors.push("missing required frontmatter field: testedVersion");
  if (!testedDate) errors.push("missing required frontmatter field: testedDate");
  if (testedDate && !/^\d{4}-\d{2}-\d{2}$/.test(testedDate)) {
    errors.push(`testedDate must be YYYY-MM-DD, got "${testedDate}"`);
  }
  if (!os) errors.push("missing required frontmatter field: os (windows | linux | macos)");
  else if (!OSES.includes(os as Os)) {
    errors.push(`os must be windows | linux | macos, got "${String(os)}"`);
  }
  if (score !== undefined && (score < 1 || score > 5)) errors.push("score must be 1–5");

  if (errors.length) throw new Error(`${slug}: ${errors.join("; ")}`);

  return {
    slug,
    title,
    titleId,
    status,
    testedVersion,
    testedDate,
    os: os as Os,
    hardware,
    score,
    gameVersion,
    screenshot,
    screenshotVerified,
    screenshots,
    notes: body,
    source,
  };
}
