/**
 * Games database. The JSON lives in src/data/games.json (generated by
 * scripts/import-games.mjs). Because this is a client-rendered SPA, the JSON
 * is loaded lazily via dynamic import so it ships only when the compatibility
 * page needs it.
 */

export type Game = {
  conceptId: number;
  titleId: string;
  allTitleIds: string[];
  name: string;
  region: string;
  cover?: string;
  publisher?: string;
  releaseDate?: string;
  genres?: string[];
  enriched?: boolean;
  noStore?: boolean;
  commentsDisabled?: boolean;
};

let gamesPromise: Promise<Game[]> | null = null;

/** Load the games database once (dynamic import keeps it out of the main bundle). */
export function loadGames(): Promise<Game[]> {
  if (!gamesPromise) {
    gamesPromise = import("../data/games.json").then((m) => m.default as Game[]);
  }
  return gamesPromise;
}

function normalize(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "");
}

/** Find a game entry for a compat report — by title ID first, then by name. */
export async function findGame(
  title: string,
  titleId?: string,
): Promise<Game | undefined> {
  const games = await loadGames();
  if (titleId) {
    const byId = games.find((g) => g.allTitleIds.includes(titleId));
    if (byId) return byId;
  }
  const key = normalize(title);
  return games.find((g) => normalize(g.name) === key);
}
